pipeline {
    
    environment {
        gitRepository = "https://github.com/nattasak13472/ascend-assignment-dev-ops.git"
        registry = "nattasak13472/ascend-assignment-nodejs"
        registryCredential = 'docker-hub'
    }
    
    agent any
    
    tools { nodejs "node" }
    
    stages {
      
        stage('Cloning Git') {
            steps {
                git gitRepository
            }
        }
        
        stage('Build') {
            steps {
                sh 'cd nodejs && npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh 'cd nodejs && npm test'
            }
        }
        
        stage('Building Image') {
            steps{
                sh "cd nodejs && docker tag ascend-assignment-nodejs " + registry + ":1.$BUILD_NUMBER && docker build -t " + registry + ":1.$BUILD_NUMBER ."
            }
        }
        
        stage('Deploy Image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential ) {
                        sh "docker push " + registry
                    }
                }
            }
        }
    
    }
}