pipeline {
    
    environment {
        registry = "nattasak13472/ascend-assignment-nodejs"
        registryCredential = 'docker-hub'
    }
    
    agent any
    
    tools { nodejs "node" }
    
    stages {
      
        stage('Cloning Git') {
            steps {
                git 'https://github.com/nattasak13472/ascend-assignment-dev-ops.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'cd nodejs && npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh 'cd nodejs && npm test'
            }
        }
        
        stage('Building image') {
            steps{
                sh "cd nodejs && docker build -t " + registry + ":$BUILD_NUMBER ."
            }
        }
        
        stage('Deploy Image') {
            steps {
                script {
                    docker.withRegistry('', registryCredential ) {
                        sh "docker push " + registry
                    }
                }
            }
        }
      
    }
}